### PR TITLE
feat(onb-204): keyword density page implemented

### PR DESCRIPTION
**Pull request by afikbae**

### CODE REVIEW

**Comment by afikbae** [comment]
hocam sayfayi ve pinia entegrasyonunu yaptim, testler uzerine calisacagim. hepsini birden pr acmaktansa parca parca yapmak daha iyi olur diye dusundum.

**Comment by yagizmumcu** [comment]
Screenshot 2024-07-16 at 10 00 53
Can you resolve errors

**Comment by yagizmumcu** [comment]
Screenshot 2024-07-16 at 10 01 44
I suppose there is an edge case about empty strings, some badges are empty

**Comment by yagizmumcu** [comment]
Screenshot 2024-07-16 at 10 04 06
Screenshot 2024-07-16 at 10 04 18
Multi-selection does not work properly

**Comment by yagizmumcu** [comment]
Screenshot 2024-07-16 at 10 05 20
Can you also change the placement of select, it overlaps with the texts

**Comment by yagizmumcu** [comment]
Screenshot 2024-07-16 at 10 10 40
Can you add a sort of validation or a text if n-gram is not applicable

**Review by yagizmumcu — APPROVED** [review]
Great and clean work 👍

**Pull request merged**
